# Generated by Django 3.2.12 on 2022-02-25 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='animal',
            field=models.CharField(choices=[('DO', 'Dog'), ('CA', 'Cat'), ('RA', 'Rabbit'), ('CO', 'Cow'), ('MO', 'Mouse'), ('PA', 'Parrot'), ('OT', 'Other')], default='DO', max_length=2),
        ),
    ]
